export const SET_OFFERS_LOADING = "SET_OFFERS_LOADING"
export const SET_OFFERS = "SET_OFFERS"
export const MAKE_OFFERS_PAGE_REQUEST = "MAKE_OFFERS_PAGE_REQUEST"
export const ON_SUCCESSFUL_OFFERS_PAGE_REQUEST = "ON_SUCCESSFUL_OFFERS_PAGE_REQUEST"
export const ON_FAILED_OFFERS_PAGE_REQUEST = "ON_FAILED_OFFERS_PAGE_REQUEST"

export const UPDATE_SETTINGS = "UPDATE_SETTINGS"

export const SET_ROUTE_TYPE = 'SET_ROUTE_TYPE';